camera0: 0
camera1: 1
frame_width: 640
frame_height: 480
mono_calibration_frames: 10
stereo_calibration_frames: 20
view_resize: 1
checkerboard_box_size_scale : 2.50
checkerboard_rows: 7
checkerboard_columns: 10
cooldown: 150

